.TH "ppstream_networkinfo" 3 "10 Mar 2016" "Version 0.9.9" "NSTDIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppstream_networkinfo \- 
.SH SYNOPSIS
.br
.PP
.SS "変数"

.in +1c
.ti -1c
.RI "char * \fBip_addr\fP"
.br
.ti -1c
.RI "char * \fBport\fP"
.br
.ti -1c
.RI "uint32_t \fBDflag\fP"
.br
.ti -1c
.RI "uint32_t \fBscflag\fP"
.br
.ti -1c
.RI "uint32_t \fBmode\fP"
.br
.in -1c

.SH "作者"
.PP 
NSTDIOのソースから Doxygen により生成しました。
