.TH "ppstearm_handlequeue" 3 "10 Mar 2016" "Version 0.9.9" "NSTDIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppstearm_handlequeue \- 
.SH SYNOPSIS
.br
.PP
.SS "変数"

.in +1c
.ti -1c
.RI "uint64_t \fBid\fP"
.br
.ti -1c
.RI "void * \fBaddr\fP"
.br
.ti -1c
.RI "int \fBtype\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "uint64_t \fBmsize\fP"
.br
.in -1c

.SH "作者"
.PP 
NSTDIOのソースから Doxygen により生成しました。
