.TH "ppstearm_handlequeue" 3 "3 Oct 2016" "Version 0.9.9" "NSTDIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppstearm_handlequeue \- 
.SH SYNOPSIS
.br
.PP
.SS "変数"

.in +1c
.ti -1c
.RI "uint64_t \fBpp_id\fP"
.br
.ti -1c
.RI "void * \fBpp_addr\fP"
.br
.ti -1c
.RI "size_t \fBpp_size\fP"
.br
.ti -1c
.RI "size_t \fBpp_compsize\fP"
.br
.ti -1c
.RI "int \fBpp_type\fP"
.br
.ti -1c
.RI "int \fBpp_status\fP"
.br
.ti -1c
.RI "double \fBpp_stime\fP"
.br
.ti -1c
.RI "double \fBpp_etime\fP"
.br
.in -1c

.SH "作者"
.PP 
NSTDIOのソースから Doxygen により生成しました。
