.TH "ppstream_handle" 3 "3 Oct 2016" "Version 0.9.9" "NSTDIO" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ppstream_handle \- 
.SH SYNOPSIS
.br
.PP
.SS "変数"

.in +1c
.ti -1c
.RI "uint64_t \fBpp_id\fP"
.br
.ti -1c
.RI "uint64_t \fBpp_msize\fP"
.br
.ti -1c
.RI "\fBppstream_networkdescriptor_t\fP * \fBnd\fP"
.br
.ti -1c
.RI "int \fBpp_hdltype\fP"
.br
.in -1c

.SH "作者"
.PP 
NSTDIOのソースから Doxygen により生成しました。
